### ISSUE TITLE
Botón sin accion 

### ISSUE THREAD

**Issue by Nidev-lab** [gonzalogg94/restaurantFront#65]
Buenas! Chicos encontré este error, al estar parado en la sección de postres el botón de Entradas  no redirige o genera ninguna accion en particular 

![image](https://user-images.githubusercontent.com/53904695/216097872-5803ec31-32fc-44b4-bb05-435baa56eb4f.png)

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by jlpereyra22** [comment]
error de boton sin accion solucionado
![image](https://user-images.githubusercontent.com/107646840/216190520-b5b5f5eb-d7f2-4fd2-88af-40ed43f689b6.png)
